export const pricing = {
  title: "Starte klein. Wachse, wenn du willst.",
  subtitle: "Du buchst nur, was du brauchst. Viele Teams starten mit einem Kanal – und erweitern, sobald der Alltag ruhiger wird.",
  frequencyLabels: { monthly: "Monatlich", annually: "Jährlich" },
  tiers: [
    {
      id: "check",
      name: "Modernisierungs‑Check",
      priceMonthly: "0",
      priceAnnually: "0",
      currency: "€",
      billedMonthlyText: "einmalig",
      billedAnnuallyText: "einmalig",
      buttonLabel: "Check starten",
      highlights: [
        "15 Minuten Gespräch",
        "2–3 konkrete Automations‑Chancen",
        "Empfehlung: welcher Kanal zuerst",
      ],
    },
    {
      id: "startklar",
      name: "AKLOW Startklar",
      priceMonthly: "ab 490",
      priceAnnually: "ab 490",
      currency: "€",
      billedMonthlyText: "einmalig",
      billedAnnuallyText: "einmalig",
      buttonLabel: "Demo buchen",
      highlights: [
        "1–2 Kanäle live (z. B. Telefon + E‑Mail)",
        "Smart Inbox & Grundwissen eingerichtet",
        "Erste Antwortvorlagen & Übergaben",
      ],
      featured: true,
    },
    {
      id: "laeuftmit",
      name: "AKLOW läuft mit",
      priceMonthly: "ab 99",
      priceAnnually: "ab 999",
      currency: "€",
      billedMonthlyText: "pro Monat",
      billedAnnuallyText: "pro Jahr",
      buttonLabel: "Anfragen",
      highlights: [
        "Feintuning & neue Antworten",
        "Neue Workflows nach Bedarf",
        "Support‑Kanal (z. B. Telegram)",
      ],
    },
  ],
  enterprise: {
    eyebrow: "Für Teams mit mehr Volumen",
    title: "Mehr Kanäle, mehr Automationen, mehr Begleitung",
    checklist: [
      "Mehrere Standorte / Nummern",
      "Individuelle Workflows & Integrationen",
      "Erweiterte Rollen & Rechte",
      "SLA‑Support",
    ],
    setupFeeAmount: "Auf Anfrage",
    setupFeeLabel: "Setup",
    monthlyAmount: "Auf Anfrage",
    monthlyLabel: "Betreuung",
    primaryCta: { label: "Mit uns sprechen", href: "/request-demo" },
    secondaryCta: { label: "Use‑Cases ansehen", href: "/use-cases" },
  },
};
